Repository Trabajitos-SV/Trabajitos-API, pull requests merged in 2023-06, with the labels that each got.

#1 adding models folder and category schema
  Trabajitos-SV-API/models/category.model.js
Labels: enhancement

#2 feature/db_missingModels
  Trabajitos-SV-API/models/municipality.model.js
  Trabajitos-SV-API/models/portfolio.model.js
  Trabajitos-SV-API/models/status.model.js
  Trabajitos-SV-API/models/trabajito.model.js
  Trabajitos-SV-API/models/user.model.js
Labels: enhancement

#3 adding Controller folder and category controller inside
  Trabajitos-SV-API/controllers/category.controller.js
Labels: enhancement

#4 adding status controller
  Trabajitos-SV-API/controllers/review.controller.js
  Trabajitos-SV-API/controllers/status.controller.js
  Trabajitos-SV-API/controllers/trabajito.controller.js
Labels: enhancement

#5 adding endTrabajito controller
  Trabajitos-SV-API/controllers/trabajito.controller.js
Labels: enhancement

#6 Feature bd models
  Trabajitos-SV-API/models/category.model.js
  Trabajitos-SV-API/models/municipality.model.js
  Trabajitos-SV-API/models/portfolio.model.js
  Trabajitos-SV-API/models/trabajito.model.js
  Trabajitos-SV-API/models/user.model.js
  Trabajitos-SV-API/package-lock.json
  Trabajitos-SV-API/package.json
Labels: bug, enhancement

#7 feat: missing controllers and pagination options added
  Trabajitos-SV-API/controllers/trabajito.controller.js
Labels: enhancement

#8 adding create and findById validator methods into portfolio calidator
  Trabajitos-SV-API/validators/index.middleware.js
  Trabajitos-SV-API/validators/portfolio.validator.js
  Trabajitos-SV-API/validators/trabajito.validators.js
Labels: enhancement

#9 feat: create auth controller, data and utils folder with files needed for auth
  Trabajitos-SV-API/controllers/auth.controller.js
  Trabajitos-SV-API/data/roles.constants.json
  Trabajitos-SV-API/utils/email.tools.js
  Trabajitos-SV-API/utils/jwt.tools.js
Labels: enhancement

#10 Feature controller portfolio
  Trabajitos-SV-API/controllers/category.controller.js
  Trabajitos-SV-API/controllers/municipality.controller.js
  Trabajitos-SV-API/controllers/portfolio.controller.js
  Trabajitos-SV-API/controllers/review.controller.js
  Trabajitos-SV-API/controllers/status.controller.js
  Trabajitos-SV-API/package-lock.json
  Trabajitos-SV-API/package.json
Labels: bug, enhancement

#11 Adding auth validator
  Trabajitos-SV-API/.DS_Store
  Trabajitos-SV-API/validators/auth.validator.js
Labels: enhancement

#12 Adding authorization method 1 to main Midddleware
  Trabajitos-SV-API/middlewares/auth.middleware.js
Labels: enhancement

#14 fix: added some validators and fixed code that caused the API crash
  Trabajitos-SV-API/app.js
  Trabajitos-SV-API/middlewares/auth.middlewares.js
  Trabajitos-SV-API/models/portfolio.model.js
  Trabajitos-SV-API/package-lock.json
  Trabajitos-SV-API/package.json
  Trabajitos-SV-API/routes/api/trabajitos.router.js
  Trabajitos-SV-API/validators/auth.validator.js
  Trabajitos-SV-API/validators/index.middleware.js
  Trabajitos-SV-API/validators/portfolio.validator.js
  Trabajitos-SV-API/validators/trabajito.validators.js
Labels: bug

#15 Fix branch
  Trabajitos-SV-API/.env
  Trabajitos-SV-API/.gitignore
  Trabajitos-SV-API/controllers/auth.controller.js
  Trabajitos-SV-API/controllers/category.controller.js
  Trabajitos-SV-API/controllers/municipality.controller.js
  Trabajitos-SV-API/controllers/portfolio.controller.js
  Trabajitos-SV-API/controllers/trabajito.controller.js
  Trabajitos-SV-API/middlewares/auth.middlewares.js
  Trabajitos-SV-API/models/portfolio.model.js
  Trabajitos-SV-API/routes/api/portfolio.router.js
  Trabajitos-SV-API/validators/trabajito.validators.js
Labels: bug
